### ISSUE TITLE
WARNING  torba.client.basenetwork:95: Timed out connecting to: lbryumx1.lbry.io:50001

### ISSUE THREAD

**Issue by sketchbuch** [lbryio/electron-starter#1]
I trying to start the starter but get this error appearing in the console. 

![image](https://user-images.githubusercontent.com/16445037/105408010-b3d0f900-5c2e-11eb-81d0-5185a954d65d.png)

All the electron app shows is "Starting sdk..."

**Comment by tzarebczan** [comment]
This repo is very outdated and doesn't have the updated lbry-sdk. You can replace it with : https://github.com/lbryio/lbry-sdk/releases/tag/v0.87.0
